apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tpexercisehelloworld-pdb
  namespace: tp-exercise
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: tpexercisehelloworld
